// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Text;

namespace generator_cli
{
    public class ZipGeoCode
    {
        public string datasetid { get; set; }
        public string recordid { get; set; }
        public Fields fields { get; set; }
        public Geometry geometry { get; set; }
        public DateTime record_timestamp { get; set; }

        public class Fields
        {
            public string city { get; set; }
            public string zip { get; set; }
            public int dst { get; set; }
            public float[] geopoint { get; set; }
            public float longitude { get; set; }
            public string state { get; set; }
            public float latitude { get; set; }
            public int timezone { get; set; }
        }

        public class Geometry
        {
            public string type { get; set; }
            public float[] coordinates { get; set; }
        }
    }
}
