// <auto-generated>
using System;
using System.Collections.Generic;
using System.Text;

namespace generator_cli.Geographic
{
    /// <summary>Information about the connectathon.</summary>
    public class ConnectathonRecord
    {
        /// <summary>Gets or sets the ccn.</summary>
        /// <value>The ccn.</value>
        [CsvHelper.Configuration.Attributes.Index(0)]
        [CsvHelper.Configuration.Attributes.Name("CCN")]
        public string CCN { get; set; }

        /// <summary>Gets or sets the name of the facility.</summary>
        /// <value>The name of the facility.</value>
        [CsvHelper.Configuration.Attributes.Index(1)]
        [CsvHelper.Configuration.Attributes.Name("Facility Name")]
        public string FacilityName { get; set; }

        /// <summary>Gets or sets the address.</summary>
        /// <value>The address.</value>
        [CsvHelper.Configuration.Attributes.Index(2)]
        [CsvHelper.Configuration.Attributes.Name("Address")]
        public string Address { get; set; }

        /// <summary>Gets or sets the city.</summary>
        /// <value>The city.</value>
        [CsvHelper.Configuration.Attributes.Index(3)]
        [CsvHelper.Configuration.Attributes.Name("City")]
        public string City { get; set; }

        /// <summary>Gets or sets the county.</summary>
        /// <value>The county.</value>
        [CsvHelper.Configuration.Attributes.Index(4)]
        [CsvHelper.Configuration.Attributes.Name("County")]
        public string County { get; set; }

        /// <summary>Gets or sets the state.</summary>
        /// <value>The state.</value>
        [CsvHelper.Configuration.Attributes.Index(5)]
        [CsvHelper.Configuration.Attributes.Name("State")]
        public string State { get; set; }

        /// <summary>Gets or sets the zip.</summary>
        /// <value>The zip.</value>
        [CsvHelper.Configuration.Attributes.Index(6)]
        [CsvHelper.Configuration.Attributes.Name("ZIP Code")]
        public string Zip { get; set; }

        /// <summary>Gets or sets the zip plus 4.</summary>
        /// <value>The zip plus 4.</value>
        [CsvHelper.Configuration.Attributes.Index(7)]
        [CsvHelper.Configuration.Attributes.Name("ZIP+4")]
        public string ZipPlus4 { get; set; }

        /// <summary>Gets or sets the type of the hospital.</summary>
        /// <value>The type of the hospital.</value>
        [CsvHelper.Configuration.Attributes.Index(8)]
        [CsvHelper.Configuration.Attributes.Name("Hospital Type")]
        public string HospitalType { get; set; }

        /// <summary>Gets or sets the longitude.</summary>
        /// <value>The longitude.</value>
        [CsvHelper.Configuration.Attributes.Index(9)]
        [CsvHelper.Configuration.Attributes.Name("Longitude")]
        public double Longitude { get; set; }

        /// <summary>Gets or sets the latitude.</summary>
        /// <value>The latitude.</value>
        [CsvHelper.Configuration.Attributes.Index(10)]
        [CsvHelper.Configuration.Attributes.Name("Latitude")]
        public double Latitude { get; set; }
    }
}
