// <auto-generated>
using System;
using System.Collections.Generic;
using System.Text;

namespace generator_cli.Geographic
{
    /// <summary>Information about the hospital.</summary>
    public class HospitalRecord
    {
        /// <summary>Gets or sets the x coordinate.</summary>
        /// <value>The x coordinate.</value>
        public double X { get; set; }

        /// <summary>Gets or sets the y coordinate.</summary>
        /// <value>The y coordinate.</value>
        public double Y { get; set; }

        /// <summary>Gets or sets the objectid.</summary>
        /// <value>The objectid.</value>
        public long OBJECTID { get; set; }

        /// <summary>Gets or sets the identifier.</summary>
        /// <value>The identifier.</value>
        public string ID { get; set; }

        /// <summary>Gets or sets the name.</summary>
        /// <value>The name.</value>
        public string NAME { get; set; }

        /// <summary>Gets or sets the address.</summary>
        /// <value>The address.</value>
        public string ADDRESS { get; set; }

        /// <summary>Gets or sets the city.</summary>
        /// <value>The city.</value>
        public string CITY { get; set; }

        /// <summary>Gets or sets the state.</summary>
        /// <value>The state.</value>
        public string STATE { get; set; }

        /// <summary>Gets or sets the zip.</summary>
        /// <value>The zip.</value>
        public string ZIP { get; set; }

        /// <summary>Gets or sets the zip 4.</summary>
        /// <value>The zip 4.</value>
        public string ZIP4 { get; set; }

        /// <summary>Gets or sets the telephone.</summary>
        /// <value>The telephone.</value>
        public string TELEPHONE { get; set; }

        /// <summary>Gets or sets the type.</summary>
        /// <value>The type.</value>
        public string TYPE { get; set; }

        /// <summary>Gets or sets the status.</summary>
        /// <value>The status.</value>
        public string STATUS { get; set; }

        /// <summary>Gets or sets the population.</summary>
        /// <value>The population.</value>
        public string POPULATION { get; set; }

        /// <summary>Gets or sets the county.</summary>
        /// <value>The county.</value>
        public string COUNTY { get; set; }

        /// <summary>Gets or sets the countyfips.</summary>
        /// <value>The countyfips.</value>
        public string COUNTYFIPS { get; set; }

        /// <summary>Gets or sets the country.</summary>
        /// <value>The country.</value>
        public string COUNTRY { get; set; }

        /// <summary>Gets or sets the latitude.</summary>
        /// <value>The latitude.</value>
        public double LATITUDE { get; set; }

        /// <summary>Gets or sets the longitude.</summary>
        /// <value>The longitude.</value>
        public double LONGITUDE { get; set; }

        /// <summary>Gets or sets the naics code.</summary>
        /// <value>The naics code.</value>
        public string NAICS_CODE { get; set; }

        /// <summary>Gets or sets information describing the naics.</summary>
        /// <value>Information describing the naics.</value>
        public string NAICS_DESC { get; set; }

        /// <summary>Gets or sets the source for the.</summary>
        /// <value>The source.</value>
        public string SOURCE { get; set; }

        /// <summary>Gets or sets the sourcedate.</summary>
        /// <value>The sourcedate.</value>
        public string SOURCEDATE { get; set; }

        /// <summary>Gets or sets the value method.</summary>
        /// <value>The value method.</value>
        public string VAL_METHOD { get; set; }

        /// <summary>Gets or sets the value date.</summary>
        /// <value>The value date.</value>
        public string VAL_DATE { get; set; }

        /// <summary>Gets or sets the website.</summary>
        /// <value>The website.</value>
        public string WEBSITE { get; set; }

        /// <summary>Gets or sets the identifier of the state.</summary>
        /// <value>The identifier of the state.</value>
        public string STATE_ID { get; set; }

        /// <summary>Gets or sets the name of the alternate.</summary>
        /// <value>The name of the alternate.</value>
        public string ALT_NAME { get; set; }

        /// <summary>Gets or sets the fips.</summary>
        /// <value>The st fips.</value>
        public string ST_FIPS { get; set; }

        /// <summary>Gets or sets the owner.</summary>
        /// <value>The owner.</value>
        public string OWNER { get; set; }

        /// <summary>Gets or sets the TTL staff.</summary>
        /// <value>The TTL staff.</value>
        public string TTL_STAFF { get; set; }

        /// <summary>Gets or sets the beds.</summary>
        /// <value>The beds.</value>
        public string BEDS { get; set; }

        /// <summary>Gets or sets the trauma.</summary>
        /// <value>The trauma.</value>
        public string TRAUMA { get; set; }

        /// <summary>Gets or sets the helipad.</summary>
        /// <value>The helipad.</value>
        public string HELIPAD { get; set; }
    }
}
