// <auto-generated>
using System;
using System.Collections.Generic;
using System.Text;

namespace generator_cli.Geographic
{
    public class HospitalRecord
    {
        public double X { get; set; }
        public double Y { get; set; }
        public long OBJECTID { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string ZIP4 { get; set; }
        public string TELEPHONE { get; set; }
        public string TYPE { get; set; }
        public string STATUS { get; set; }
        public string POPULATION { get; set; }
        public string COUNTY { get; set; }
        public string COUNTYFIPS { get; set; }
        public string COUNTRY { get; set; }
        public double LATITUDE { get; set; }
        public double LONGITUDE { get; set; }
        public string NAICS_CODE { get; set; }
        public string NAICS_DESC { get; set; }
        public string SOURCE { get; set; }
        public string SOURCEDATE { get; set; }
        public string VAL_METHOD { get; set; }
        public string VAL_DATE { get; set; }
        public string WEBSITE { get; set; }
        public string STATE_ID { get; set; }
        public string ALT_NAME { get; set; }
        public string ST_FIPS { get; set; }
        public string OWNER { get; set; }
        public string TTL_STAFF { get; set; }
        public string BEDS { get; set; }
        public string TRAUMA { get; set; }
        public string HELIPAD { get; set; }
    }
}
